name: auto_ml/DS-AP-Capstone-Project
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - alsa-lib=1.2.14=hb9d3cd8_0
  - anaconda-anon-usage=0.7.1=py313hfc0e8ea_100
  - annotated-types=0.6.0=py313h06a4308_0
  - archspec=0.2.3=pyhd3eb1b0_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - boltons=24.1.0=py313h06a4308_0
  - brotli=1.1.0=hb9d3cd8_3
  - brotli-bin=1.1.0=hb9d3cd8_3
  - brotli-python=1.0.9=py313h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.7.14=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - certifi=2025.7.14=pyhd8ed1ab_0
  - cffi=1.17.1=py313h1fdaa30_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - comm=0.2.2=pyhd8ed1ab_1
  - conda=25.5.1=py313h06a4308_0
  - conda-anaconda-telemetry=0.1.2=py313h06a4308_1
  - conda-anaconda-tos=0.2.0=py313h06a4308_0
  - conda-content-trust=0.2.0=py313h06a4308_1
  - conda-libmamba-solver=25.4.0=pyhd3eb1b0_0
  - conda-package-handling=2.4.0=py313h06a4308_0
  - conda-package-streaming=0.11.0=py313h06a4308_0
  - contourpy=1.3.2=py313h33d0bda_0
  - cpp-expected=1.1.0=hdb19cb5_0
  - cpython=3.13.5=py313hd8ed1ab_102
  - cryptography=45.0.3=py313h2ccb017_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dbus=1.16.2=h3c4dab8_0
  - debugpy=1.8.15=py313h5d5ffb9_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - distro=1.9.0=py313h06a4308_0
  - double-conversion=3.3.1=h5888daf_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - fmt=11.1.4=h07f6e7f_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.59.0=py313h3dea7bd_0
  - freetype=2.13.3=ha770c72_1
  - frozendict=2.4.2=py313h06a4308_0
  - graphite2=1.3.14=h5888daf_0
  - harfbuzz=11.2.1=h3beb420_0
  - icu=75.1=he02047a_0
  - idna=3.7=py313h06a4308_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=9.4.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.7=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - joblib=1.5.1=pyhd8ed1ab_0
  - jsonpatch=1.33=py313h06a4308_1
  - jsonpointer=2.1=pyhd3eb1b0_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - jupyterlab_widgets=3.0.15=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.8=py313h33d0bda_1
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h0aef613_1
  - libarchive=3.8.1=gpl_h98cc613_100
  - libblas=3.9.0=32_h59b9bed_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_3
  - libbrotlidec=1.1.0=hb9d3cd8_3
  - libbrotlienc=1.1.0=hb9d3cd8_3
  - libcblas=3.9.0=32_he106b2a_openblas
  - libclang-cpp20.1=20.1.8=default_hddf928d_0
  - libclang13=20.1.8=default_ha444ac7_0
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.14.1=h332b0f4_0
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.125=hb9d3cd8_0
  - libedit=3.1.20230828=h5eee18b_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=h7f8727e_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_3
  - libgcc-ng=15.1.0=h69a702a_3
  - libgfortran=15.1.0=h69a702a_3
  - libgfortran5=15.1.0=hcea5267_3
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.2=h3618099_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.1.0=h767d61c_3
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=32_h7ac8fdf_openblas
  - libllvm20=20.1.8=hecd9e04_0
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libmamba=2.3.0=h44402ff_1
  - libmambapy=2.3.0=py313h4f2f577_1
  - libmpdec=4.0.0=h5eee18b_0
  - libnghttp2=1.64.0=h161d5f1_0
  - libntlm=1.8=hb9d3cd8_0
  - libopenblas=0.3.30=pthreads_h94d23a6_0
  - libopengl=1.7.0=ha4b6fd6_2
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h943b412_0
  - libpq=17.5=h27ae623_0
  - libsodium=1.0.20=h4ab18f5_0
  - libsolv=0.7.34=h9463b59_0
  - libsqlite=3.50.3=hee844dc_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_3
  - libstdcxx-ng=15.1.0=h4852527_3
  - libtiff=4.7.0=hf01ce69_5
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.10.0=h65c71a3_0
  - libxml2=2.13.8=h4bc477f_0
  - libxslt=1.1.39=h76b75d6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=hd590300_1001
  - mamba=2.3.0=h233bd08_1
  - markdown-it-py=2.2.0=py313h06a4308_1
  - matplotlib=3.10.3=py313h78bf25f_0
  - matplotlib-base=3.10.3=py313h129903b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mdurl=0.1.0=py313h06a4308_0
  - menuinst=2.2.0=py313h06a4308_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nlohmann_json=3.11.3=he02047a_1
  - numpy=2.3.1=py313hf6604e3_1
  - openjpeg=2.5.3=h5fbd93e_0
  - openldap=2.6.10=he970967_0
  - openssl=3.5.1=h7b32b05_0
  - packaging=24.2=py313h06a4308_0
  - parso=0.8.4=pyhd8ed1ab_1
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.45=hc749103_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py313h8db990d_0
  - pixman=0.46.2=h29eaf8c_0
  - platformdirs=4.3.7=py313h06a4308_0
  - pluggy=1.5.0=py313h06a4308_0
  - polars=1.31.0=default_h70f2ef1_1
  - polars-default=1.31.0=py39hf521cc8_1
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py313h536fd9c_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.6=py313h5eee18b_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=2.10.3=py313h06a4308_0
  - pydantic-core=2.27.1=py313h4aa5aa6_0
  - pygments=2.19.1=py313h06a4308_0
  - pyodbc=5.2.0=py313h46c70d0_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyside6=6.9.1=py313h7dabd7a_0
  - pysocks=1.7.1=py313h06a4308_0
  - python=3.13.5=hec9711d_102_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.13.5=h4df99d1_102
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.13=0_cp313
  - pytz=2025.2=pyhd8ed1ab_0
  - pyzmq=27.0.0=py313h8e95178_0
  - qhull=2020.2=h434a139_5
  - qt6-main=6.9.1=h0384650_1
  - readline=8.2=h5eee18b_0
  - reproc=14.2.4=h6a678d5_2
  - reproc-cpp=14.2.4=h6a678d5_2
  - requests=2.32.3=py313h06a4308_1
  - rich=13.9.4=py313h06a4308_0
  - ruamel.yaml=0.18.10=py313h5eee18b_0
  - ruamel.yaml.clib=0.2.12=py313h5eee18b_0
  - scipy=1.16.0=py313h86fcf2b_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - simdjson=3.13.0=h84d6215_0
  - six=1.17.0=pyhd8ed1ab_0
  - spdlog=1.15.3=h10b92b3_0
  - sqlite=3.50.3=heff268d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py313h29aa505_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_hd72426e_102
  - tornado=6.5.1=py313h536fd9c_0
  - tqdm=4.67.1=py313h7040dfc_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - truststore=0.10.0=py313h06a4308_0
  - typing-extensions=4.12.2=py313h06a4308_0
  - typing_extensions=4.12.2=py313h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - unixodbc=2.3.12=h661eb56_0
  - urllib3=2.3.0=py313h06a4308_0
  - wayland=1.24.0=h3e06ad9_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py313h06a4308_0
  - widgetsnbextension=4.0.14=pyhd8ed1ab_0
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.45=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml-cpp=0.8.0=h6a678d5_1
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py313h536fd9c_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - appdirs==1.4.4
      - beautifulsoup4==4.14.2
      - blinker==1.9.0
      - click==8.3.0
      - curl-cffi==0.13.0
      - flask==3.1.2
      - html5lib==1.1
      - iniconfig==2.1.0
      - itsdangerous==2.2.0
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.2.1
      - jeepney==0.9.0
      - jinja2==3.1.6
      - keyring==25.6.0
      - lask==0.2.1
      - lxml==6.0.2
      - markupsafe==3.0.3
      - more-itertools==10.7.0
      - multitasking==0.0.12
      - nuvolos-odbc==0.5.1
      - pandas==2.2.3
      - peewee==3.18.2
      - pip==25.2
      - protobuf==6.32.1
      - pyarrow==21.0.0
      - pytest==8.4.2
      - pyyaml==6.0.3
      - scikit-learn==1.6.1
      - secretstorage==3.3.3
      - setuptools==80.9.0
      - soupsieve==2.8
      - webencodings==0.5.1
      - websockets==15.0.1
      - werkzeug==3.1.3
      - yfinance==0.2.66
prefix: /opt/conda
